# Thème « The Matrix » — vert phosphore sur noir
# À appliquer : soit `include matrix.conf` dans kitty.conf (global),
# soit par fenêtre :  kitty @ set-colors -a ~/.config/kitty/matrix.conf

foreground            #00ff41
background            #000000
selection_foreground  #000000
selection_background  #00ff41
cursor                #00ff41
cursor_text_color     #000000
url_color             #39ff14

# Palette 16 couleurs (déclinaisons de vert — look monochrome)
color0  #0d0208
color8  #005f1f
color1  #008f11
color9  #00ff41
color2  #00ff41
color10 #39ff14
color3  #00cc33
color11 #66ff66
color4  #006622
color12 #00aa22
color5  #00d17a
color13 #33ffaa
color6  #00ffcc
color14 #66ffdd
color7  #00cc44
color15 #ccffcc
